/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newsgyan;

import client.RecieveUserInfo;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;

/**
 *
 * @author Vibhu007
 */
public class Primary extends javax.swing.JFrame {

    /**
     * Creates new form Primary
     */
    static Preferences pref = Preferences.userNodeForPackage(Primary.class);
    public Primary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getStarted = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getStarted.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        getStarted.setForeground(new java.awt.Color(255, 161, 89));
        getStarted.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getStarted.setText("GET STARTED");
        getStarted.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getStarted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getStartedMouseClicked(evt);
            }
        });
        getContentPane().add(getStarted, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 230, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 161, 89));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Stay updated ....");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 240, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getStartedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getStartedMouseClicked
        Login login = new Login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_getStartedMouseClicked

    private static boolean checkLoginStatus() {
        return pref.getInt("status", 2) == 1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Primary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Primary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Primary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Primary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new Primary().setVisible(true);
            Primary primary = new Primary();
            primary.setVisible(true);
            if(checkLoginStatus())
            {
                String uname = pref.get("user", "-1234");
                
                RecieveUserInfo ob = new RecieveUserInfo(uname);
                if(!ob.recieveUserInfo())
                    JOptionPane.showMessageDialog(null , "Some error occured, all functionalities might not work");
                
                openHomePage();
                primary.dispose();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel getStarted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private static void openHomePage() {
        Home home = new Home();
        home.setVisible(true);
        //home.pack();
        home.setLocationRelativeTo(null);

    }
}
