/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newsgyan;

import client.UserInfoUpdateClient;
import client.VlogClient;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import model.User;
import model.Vlog;
import ui.RendererVlog;
import utility.VlogsInfoGenerator;

/**
 *
 * @author Vibhu007
 */
public class VlogView extends javax.swing.JFrame {

    /**
     * Creates new form VlogView
     */
    
    DefaultListModel<Vlog> listModel;
    private ArrayList<Vlog> vlogs;
    
    public VlogView() {
        initComponents();
        VlogsInfoGenerator obj = new VlogsInfoGenerator();
        this.vlogs = obj.getAllVlogs();
        listModel = new DefaultListModel<>();
        this.vlogs.forEach((n) -> {
            listModel.addElement(n);
        });
        this.vlogList.setModel(listModel);
        
        this.vlogList.setCellRenderer(new RendererVlog());
        
        customWindowClosing();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        postVlogButton = new javax.swing.JButton();
        searchByReporter = new javax.swing.JTextField();
        searchByReporterButton = new javax.swing.JButton();
        allVlogsButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vlogList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back-button.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vlogs");

        postVlogButton.setText("Post your Vlog");
        postVlogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postVlogButtonActionPerformed(evt);
            }
        });

        searchByReporterButton.setText("Search by reporter");
        searchByReporterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByReporterButtonActionPerformed(evt);
            }
        });

        allVlogsButton.setText("All Vlogs");
        allVlogsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allVlogsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(searchByReporter, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchByReporterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(allVlogsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(postVlogButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchByReporter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchByReporterButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(postVlogButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(allVlogsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1160, 80));

        vlogList.setModel(new javax.swing.AbstractListModel<Vlog>() {
            Vlog[] vlogs = { };
            public int getSize() { return vlogs.length; }
            public Vlog getElementAt(int i) { return vlogs[i]; }
        });
        vlogList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vlogListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vlogList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1160, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        openHomePage();
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchByReporterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByReporterButtonActionPerformed
        String uname = searchByReporter.getText();
        if(!uname.isEmpty()){
            VlogsInfoGenerator obj = new VlogsInfoGenerator();
            this.vlogs = obj.getUserVlogs(uname);
            listModel = new DefaultListModel<>();
            this.vlogs.forEach((n) -> {
                listModel.addElement(n);
        });
        this.vlogList.setModel(listModel);
        }
        else{
            JOptionPane.showMessageDialog(null , "Empty fields not allowed");
        }
    }//GEN-LAST:event_searchByReporterButtonActionPerformed

    private void vlogListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vlogListMouseClicked
        
        // selecting even if right mouse button is clicked
            if ( evt.getButton() == MouseEvent.BUTTON3 )
            {
                int row = vlogList.locationToIndex(evt.getPoint());
                vlogList.setSelectedIndex(row);
            }
            
            Vlog vlog = (Vlog) vlogList.getSelectedValue();
            
            if(evt.getButton() == MouseEvent.BUTTON1) 
            {
                // view the vlog
                viewVlog(vlog);
            }
            if(evt.getButton() == MouseEvent.BUTTON3)
            {
                // upvote procedure 
                JPopupMenu popup = new JPopupMenu();
                JMenuItem upvote = new JMenuItem("Upvote this vlog");
                
                upvote.addActionListener( (ActionEvent e) -> {
                    int ind = vlogList.getSelectedIndex();
                    Vlog vlog1 = (Vlog) vlogList.getSelectedValue();
                    if(upvoteVlog(vlog1)) {
                    
                        int currUpvote = vlog1.getUpvotes();
                        vlog1.setUpvotes(currUpvote+1);
                        vlogs.set(ind, vlog1);
                        User.getVotedVlogs().add(vlog.getReporter()+"_"+vlog.getTimeStamp());

                        this.listModel.clear();
                        this.vlogs.forEach((n) -> {
                            listModel.addElement(n);
                        });
                        this.vlogList.setModel(listModel);
                        this.vlogList.setCellRenderer(new RendererVlog());

                        JOptionPane.showMessageDialog(null , "Vote registered !");
                    }
                    
                });
                
                popup.add(upvote);
                vlogList.setComponentPopupMenu(popup);
            }
    }//GEN-LAST:event_vlogListMouseClicked

    private void postVlogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postVlogButtonActionPerformed
        PostVlog obj = new PostVlog();
        obj.setVisible(true);
        obj.pack();
        obj.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_postVlogButtonActionPerformed

    private void allVlogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allVlogsButtonActionPerformed
        searchByReporter.setText(null);
        VlogsInfoGenerator obj = new VlogsInfoGenerator();
            this.vlogs = obj.getAllVlogs();
            listModel = new DefaultListModel<>();
            this.vlogs.forEach((n) -> {
                listModel.addElement(n);
        });
        this.vlogList.setModel(listModel);
    }//GEN-LAST:event_allVlogsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VlogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VlogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VlogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VlogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VlogView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allVlogsButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton postVlogButton;
    private javax.swing.JTextField searchByReporter;
    private javax.swing.JButton searchByReporterButton;
    private javax.swing.JList<Vlog> vlogList;
    // End of variables declaration//GEN-END:variables
    
    private static void openHomePage() {
        Home home = new Home();
        home.setVisible(true);
        home.setLocationRelativeTo(null);
    }
    
    private void customWindowClosing() {
        this.addWindowListener(new WindowAdapter(){
            @Override
        public void windowClosing(java.awt.event.WindowEvent windowEvent) {
            
            UserInfoUpdateClient obj1 = new UserInfoUpdateClient();
                if(!(obj1.updateUserInfo()))
                    JOptionPane.showMessageDialog(null , "Some error occured");
                
            }
        });
    }

    private boolean upvoteVlog(Vlog vlog) {
        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if(User.getInstance().getUserName() != null) {
            
            if(User.getVotedVlogs().contains(vlog.getReporter()+"_"+vlog.getTimeStamp())) {
                JOptionPane.showMessageDialog(null , "Already voted!");
                return false;
            }
            
            VlogClient obj = new VlogClient();
            if( obj.upvoteVlog(vlog.getReporter(), vlog.getTimeStamp()) ) {
                return true;
            }
            else {
                JOptionPane.showMessageDialog(null , "Could not register vote");
            }
        }
        else {
            JOptionPane.showMessageDialog(null , "Login to upvote!");
        }
        return false;
    }

    private void viewVlog(Vlog vlog) {
        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        VlogClient obj = new VlogClient();
        String port = obj.getPortForVideoStream(vlog.getReporter(), vlog.getTimeStamp(), vlog.getExtension());
        if(port.compareTo("") != 0) {
            MediaPanel.main(new String[] {port});
        }
        else
            JOptionPane.showMessageDialog(null , "Some error occured or server busy");
    }

}
